image: smitea/eth-toolbox-amd64
stages:
  - build
  - test
  - security
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - cache/
    - artifacts/
    - docs/
    - .env

build:
  stage: build
  script:
    - cp .env.sample .env
    - git config --global http.sslVerify false
    - yarn config set registry https://registry.npmmirror.com
    - npm config set registry https://registry.npm.taobao.org
    - yarn && yarn build

test:
  stage: test
  script:
    - yarn coverage
  coverage: '/(All files)\W+(98|99|100)\W+(98|99|100)\W+(98|99|100)\W+(98|99|100)/'
  needs: ["build"]

slither:
  stage: security
  script:
    - yarn slither
  needs: ["test"]

deploy:anvil:
  stage: deploy
  script:
    - yarn deploy anvil
  needs: ["slither"]